### PR TITLE
Setup styling with tailwind css

### PR DESCRIPTION
**Pull request by Evaristekanova**
### what does this PR do?

- adding tailwind CSS in this project
- adding tailwind config file 
- adding postcss config file

### how to test this manually?

- clone this repo
- run `npm install`
- run `npm run dev`

### screenshoot

- this is how it looks on large screen 

Screenshot (5)

- this is how it looks on small device

Screenshot (6)

ch[finish setup styling with tailwind css]

### CODE REVIEW

**Review by Aimeana100 — APPROVED** [review]
Hello dear @Evaristekanova ,  Thanks for your work. the codes runs very smoothly 👍

**Review by Kevin-ishimwe — APPROVED** [review]
great work

**Review by FabCode67 — APPROVED** [review]

**Review by Christabll — APPROVED** [review]

**Review by mansurissa — APPROVED** [review]
LGTM

**Comment by Evaristekanova** [comment]
[Setup styling](https://trello.com/c/fiOgiIXt/46-setup-styling)

**Pull request merged**
