### PR TITLE
#80 chore for admin dashboard template

### PR DESCRIPTION
**Pull request by FabCode67**
### how does this PR do?
- to create admin dashboard template with static sidebar and navbar

### Description of Task to be completed?
have this endpoints:
- /dashboard
- /dashboard/user
- /dashboard/product
- /dashboard/customer
- /dashboard/setting
- /dashboard/message
- /dashboard/notifications
- /dashboard/order

### how this should be tested?
- git clone from repo
- git checkout into ch-dashboard-template-80
- run npm i
- run npm run dev in your terminal
### screenshoots
Screen Shot 2023-04-28 at 15 41 46
Screen Shot 2023-04-28 at 15 42 21
Screen Shot 2023-04-28 at 15 43 39
Screen Shot 2023-04-28 at 15 44 11

### CODE REVIEW

**Comment by Aimeana100** [comment]
@FabCode67  good job fab.

**Review by Aimeana100 — COMMENTED** [review]
Hello, @FabCode67 , you have done a good job man. 
but it could be much better if you try to implement a simple footer and  stop it from overlapping the other contents, like that sidebar.

image

**Comment by FabCode67** [comment]
> Hello, @FabCode67 , you have done a good job man. but it could be much better if you try to implement a simple footer and stop it from overlapping the other contents, like that sidebar.
> 
> image

done

**Review by Aimeana100 — APPROVED** [review]
You did a good job @FabCode67

**Review by Christabll — APPROVED** [review]

**Review by Evaristekanova — APPROVED** [review]

**Review by mansurissa — APPROVED** [review]

**Pull request merged**
