### PR TITLE
chore-setup reduxtoolkit#42

### PR DESCRIPTION
**Pull request by BenoitIT**
### what were done here  on that PR

- install redux/toolkit and react-redux dependancies
- reaate states store
- create reducer function and define events right there
- demostrate who things work on user interface finished

### how this can be tested
- clone https://github.com/atlp-rwanda/ecommerce-app-legends-fe and switch to `ch-Setup-Redux#42`
- run npm i install in your terminal
-  run npm run dev to start app on web browser
-  click the buttons there to see how they are dynamically render the contents

### CODE REVIEW

**Review by Aimeana100 — APPROVED** [review]
Good job, @BenoitIT .

**Review by Kevin-ishimwe — APPROVED** [review]
great work

**Review by Aimeana100 — COMMENTED** [review]
This also work very perfect, it has basic setup of react redux running.

however it has conflicts with develop branch that should be resolved.

**Comment by BenoitIT** [comment]
thanks all get fixed

**Review by Aimeana100 — APPROVED** [review]
Great, @BenoitIT .

**Review by FabCode67 — APPROVED** [review]

**Review by mansurissa — APPROVED** [review]

**Pull request merged**
