### PR TITLE
#60 Ft user profile 

### PR DESCRIPTION
**Pull request by Evaristekanova**
### What does this PR Do?

- adding page to update user
- adding update user link in navbar
- add translation of everything on update user page

### how to test this manually

- run `npm i` or `npm install`
- run `npm run dev`
- click on the link in terminal and add `/settings`

### screenshoot

- Desktop version 

Screenshot (24)

- Mobile version

Screenshot (25)

### CODE REVIEW

**Review by FabCode67 — APPROVED** [review]
good

**Review by Aimeana100 — CHANGES_REQUESTED** [review]
Great @Evaristekanova , but i wonder what should be if you create a change passwrd form that work independt from other user Information.

**Review by Aimeana100 — APPROVED** [review]
well

**Review by Aimeana100 — APPROVED** [review]
well

**Review by Christabll — APPROVED** [review]

**Review by Christabll — APPROVED** [review]

**Review by mansurissa — APPROVED** [review]

**Pull request merged**
